### ISSUE TITLE
ImportError: No module named mn_iot.mac80211.cli

### ISSUE THREAD

**Issue by deepakrishnan84** [ramonfontes/mininet-iot#1]
Hi,

Am net to mininet. Installed mininet VM. Cloned your repo and tried to run eg. 6LoWPan.py

I get the following error

```
Traceback (most recent call last):
     File "6LoWPan.py", line 7, in <module>
        from mn_iot.mac80211.cli import CLI_wifi
 ImportError: No module named mn_iot.mac80211.cli
```
Tried in a Ubuntu VM. Cloned your repo after installing mininet. Removed multiple versions of python. Set PYTHONPATH to the example directory. I still get the error.
Kindly help
Deepa Krishnan

**Comment by ramonfontes** [comment]
Please use https://github.com/intrig-unicamp/mininet-wifi instead.
