### ISSUE TITLE
ImportError: No module named sixLoWPAN.link

### ISSUE THREAD

**Issue by IntidharBE** [ramonfontes/mininet-iot#2]
Hi, 
Tried to run the example iot.py but I got the folowing error:

Traceback (most recent call last):
  File "/mininet-iot/examples/iot.py", line 10, in <module>
    from mn_iot.mac80211.sixLoWPAN.link import sixLoWPANLink
**ImportError: No module named sixLoWPAN.link**

Kindly Help
Thanks 
Intidhar

**Comment by ramonfontes** [comment]
Please use Mininet-WiFi and https://github.com/intrig-unicamp/mininet-wifi/blob/master/examples/6LoWPan.py instead.
